server:
  port: 8091
spring:
  main:
    allow-bean-definition-overriding: true
  # 配置mysql数据源
  datasource:
    druid:
      username: root
      password: root
      url: jdbc:mysql://47.105.39.86:3306/stock?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
      driver-class-name: com.mysql.jdbc.Driver
      # 初始化时建立物理连接的个数。初始化发生在显示调用 init 方法，或者第一次 getConnection 时
      initialSize: 6
      # 最小连接池数量
      minIdle: 2
      # 最大连接池数量
      maxActive: 20
      # 获取连接时最大等待时间，单位毫秒。配置了 maxWait 之后，缺省启用公平锁，
      # 并发效率会有所下降，如果需要可以通过配置 useUnfairLock 属性为 true 使用非公平锁。
      maxWait: 60000
      #对配置已开启的 filters 即 stat(sql 监控)wall（防火墙）
      stat-view-servlet:  # 监控页配置
        enabled: true  # 是否启用监控页
        login-username: admin  # 登录用户名
        login-password: admin  # 登录密码
        resetEnable: false  # 是否允许重置监控配置

      web-stat-filter:  # Web监控
        enabled: true  # 是否启用Web监控
        urlPattern: /*  # URL匹配模式
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'  # 排除项，不进行Web监控的URL

      filter:
        stat:  # SQL监控
          slow-sql-millis: 1000  # SQL执行时间阈值，超过该阈值将被记录
          logSlowSql: true  # 是否记录慢SQL
          enabled: true  # 是否启用SQL监控
        wall:  # 防火墙
          enabled: true  # 是否启用防火墙
          config:
            drop-table-allow: false  # 是否允许执行删除表的操作
  profiles:
    active: stock
# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml # 配置加载mapper.xml资源
  type-aliases-package: com.chenhai.stock.pojo.entity # 批量给实体类取别名, 方便xml直接使用别名, 避免冗余
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 通过mybatis执行的sql以日志方式输出到终端 方便调试
# 配置分页插件
pagehelper:
  helper-dialect: mysql # 配置分页方言(数据库类型)
  reasonable: true # 开启合理查询 比如共100页时, 查询101页 默认查询最后一页 查询-1页时默认查询第一页

